### ISSUE TITLE
Get `ARGON2_ENCODING_FAIL` with long salt because of the fix encoded buffer size

### ISSUE THREAD

**Issue by ichaozai** [thibaultCha/lua-argon2-ffi#8]
The `ENCODED_LEN` is fix to 108.
When the salt is long and the encoded hash exceeds this size, `encrypt` fails and gets `ARGON2_ENCODING_FAIL` error.

Use variable encoded buffer size can solve this problem.

**Comment by thibaultcha** [comment]
Thanks for reporting. I'm quite busy at the moment but I would welcome a PR to address this!

**Comment by thibaultcha** [comment]
I just released version `3.0.0` of this module which is based on lua-argon2's `3.0.0` as well (they are interoperable). Consider this resolved, thank you for the report :)
